-- Migration: test_migration
-- Generated: 2025-09-08 11:11:36
-- Database Type: SQLite
-- 🎯 Generated by Schemer - The Ultimate Database Schema Diff Tool

BEGIN TRANSACTION;

-- Modify table: main.users
-- SQLite does not support ALTER COLUMN. Manual migration required for main.users.name

-- Modify table: main.products
-- SQLite does not support ALTER COLUMN. Manual migration required for main.products.price

COMMIT;

-- Migration completed successfully! 🎉
-- Review this script carefully before executing in production.
